export const designSystemCopy = {
  title: 'Kimino 컴포넌트 라이브러리',
  introduction: '앱에서 사용하는 실제 컴포넌트입니다. 상태를 조작하고 나란히 비교해 보세요.',
  scope: '합성 데이터만 사용합니다. 서버 요청·계정 연결·게시·저장은 하지 않습니다.',
  themeLabel: '테마',
  systemTheme: '시스템',
  lightTheme: '밝게',
  darkTheme: '어둡게',
  foundations: '기초 토큰',
  buttons: '버튼',
  fields: '입력 필드',
  actions: '게시글과 반응',
  composer: '작성기',
  enabled: '활성',
  disabled: '비활성',
  busy: '진행 중',
  busyAction: '처리 중…',
  action: '계속하기',
  iconAction: '추가',
  normalField: '기본 입력',
  filledField: '값이 있는 입력',
  disabledField: '비활성 입력',
  invalidField: '오류가 있는 입력',
  textarea: '여러 줄 입력',
  placeholder: '입력할 내용을 적어 주세요',
  sampleValue: '입력된 내용',
  invalidHelp: '입력값을 다시 확인해 주세요.',
  rest: '기본 상태',
  selected: '좋아요·저장 선택',
  pending: '반응 처리 중',
  warning: '경고가 있는 글',
  samplePost: '오늘은 조금 천천히 읽어요. 작은 이야기에 집중할 수 있는 화면을 만들고 있어요.',
  sampleParent: '커피 한 잔과 함께 시작하는 아침이에요.',
  sampleWarning: '이야기의 결말이 포함돼요',
  localAction: '컴포넌트 동작을 확인했어요. 외부로 전송하지 않았어요.',
  draft: '본문을 입력하면 작성 옵션과 게시 버튼 상태가 바뀝니다.',
  failed: '게시 실패 예시',
  failureText: '예시 오류입니다. 잠시 후 다시 시도해 주세요.',
  idleComposer: '새 글 작성',
  failureComposer: '오류와 초안',
};
